In [5]:
x= [(0.8,0.3,0.1,0),(0.2,0,0,0.3),(0.3,0.6,0,0.7)]
import pandas as pd
import numpy as np

In [6]:
p = pd.DataFrame(x)
p
n = np.array(x)

In [8]:
n

array([[0.8, 0.3, 0.1, 0. ],
       [0.2, 0. , 0. , 0.3],
       [0.3, 0.6, 0. , 0.7]])

In [11]:
n.argsort(axis = 1)

array([[3, 2, 1, 0],
       [1, 2, 0, 3],
       [2, 0, 1, 3]])

In [10]:
n.argsort(axis = 0)[:,-1]

array([0, 1, 2])

In [13]:
np.random.randint(2,2)


ValueError: low >= high

In [ ]:
import tensorflow as tf
A = tf.zeros([0, 4])
A
l = (1, 2, 3, 4)
  
# Printing the input
print('l: ', l)
  
# Calculating result
x = tf.convert_to_tensor(l, dtype = tf.float64)
  
  
# Printing the result
print('x: ', x)

In [1]:
shape(2,1,2)

NameError: name 'shape' is not defined

In [2]:
import numpy as np
a = np.random.rand(3,5)
b = np.random.rand(4,3)

a
b

array([[0.40891427, 0.25658263, 0.64811458],
       [0.99605531, 0.75567394, 0.82806954],
       [0.3440789 , 0.5277562 , 0.68483082],
       [0.69704147, 0.51755098, 0.83087612]])

In [16]:
a.T+b.sum(axis=0)

array([[3.03634865, 2.80623589, 3.86015167],
       [2.74343823, 2.54482515, 3.06274547],
       [3.38815806, 2.70158051, 3.49800716],
       [2.82118845, 2.74598891, 3.59898266],
       [3.18693055, 3.01162424, 3.14016427]])

In [5]:
import pandas as pd
df = pd.read_csv("../../taipy/taipy-project/data/restaurants.csv")

In [20]:
address = df["full_address"].str.split(",", 3, expand=True)
address.loc[:,2].unique()

/var/folders/16/sj7htwpn37x5chbjt67h8nrr0000gn/T/ipykernel_12886/1633975459.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  address = df["full_address"].str.split(",", 3, expand=True)


array([' AL', ' Fultondale', ' Birmingham', nan, ' Homewood', ' Hoover',
       ' USA', ' Dothan', '3', ' Huntsville', ' Decatur', ' Gulf Shores',
       ' WY', ' WI', ' Ashwaubenon', ' Baraboo', ' Lake Delton',
       ' Brookfield', ' Oak Creek', ' Hales Corners', ' Wauwatosa',
       ' Milwaukee', ' Village of Pewaukee', ' Waunakee', ' Waukesha',
       ' Monona', '', ' Kenosha', ' Pleasant Prairie', ' Mt. Pleasant',
       ' MN', ' Duluth', ' Green Bay', ' Howard', ' Sheboygan',
       ' Madison', ' Janesville', ' Village of', ' IL', ' Spring Grove',
       ' Gurnee', ' WV', ' Vienna', ' Morgantown', ' Parkersburg',
       ' Charleston', ' Martinsburg', ' Kanawha City', ' OH',
       ' Huntington', ' WA', ' Olympia', ' Lacey', ' Seattle', ' Everett',
       ' Edmonds', ' Lynnwood', ' Mukilteo', ' Bothell', ' 西雅图',
       ' Alderwood Manor', ' Kirkland', ' Mill Creek', ' Suite B-1',
       ' seattle', ' Bellevue', ' Snohomish', ' Redmond', ' Duvall',
       ' Kennewick', ' Pasco', ' 